sudo: false
language: java
install: true
script:
  - mvn clean test -Dmaven.test.redirectTestOutputToFile=true -P travis
  - mvn jacoco:report -P travis
branches:
  only:
  - develop
jdk:
  - openjdk9

after_success:
  - bash <(curl -s https://codecov.io/bash)
